cookbook_path ['/vagrant/cookbooks']
cookbook_path ['/vagrant/cookbooks']
cookbook_path ['/vagrant/cookbooks']
cookbook_path ['/vagrant/cookbooks']
cookbook_path ['/vagrant/cookbooks']
cookbook_path ['/vagrant/cookbooks']
